INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('de','German', CURRENT_TIMESTAMP);
INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('en','English', CURRENT_TIMESTAMP);
INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('fr','French', CURRENT_TIMESTAMP);
INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('it','Italian', CURRENT_TIMESTAMP);
INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('pl','Polish', CURRENT_TIMESTAMP);

