INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('en','English', CURRENT_TIMESTAMP);
INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('fr','French', CURRENT_TIMESTAMP);
INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('in','Indonesian', CURRENT_TIMESTAMP);
INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('ar','Arabic', CURRENT_TIMESTAMP);
INSERT INTO language (LANGUAGE_CODE, LANGUAGE_NAME, INSERT_TIME) VALUES ('ja','Japanese', CURRENT_TIMESTAMP);
