DROP TABLE IF EXISTS language;

CREATE TABLE IF NOT EXISTS language (
    id SERIAL PRIMARY KEY,
    LANGUAGE_CODE CHAR(2) NOT NULL,
    LANGUAGE_NAME VARCHAR(30),
    INSERT_TIME TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS langIndex ON language (LANGUAGE_CODE);
